apiVersion: v1
kind: Service
metadata:
  name: career-connect-backend-service
  namespace: "<NAMESPACE>"
spec:
  selector:
    app: career-connect-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
