apiVersion: v1
kind: Service
metadata:
  name: career-connect-frontend-service
  namespace: "<NAMESPACE>"
spec:
  selector:
    app: career-connect-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
