apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: career-connect-ingress
  namespace: "<NAMESPACE>"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: career-connect.imcc.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: career-connect-frontend-service
                port:
                  number: 80
